name: CD

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Build API Image
      run: docker build -t yijian-api:${{ github.ref_name }} -f docker/Dockerfile.api ./apps/api
      
    - name: Build Web Image
      run: docker build -t yijian-web:${{ github.ref_name }} -f docker/Dockerfile.web ./apps/web
